import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{BrowserRouter,Routes,Route,Navigate,Link,useNavigate,useParams}from'react-router-dom';
import'./style.css';
const API='http://localhost:8080';
async function api(path,opt={}){
 const r=await fetch(API+path,{credentials:'include',headers:{'Content-Type':'application/json'},...opt});
 let d={};try{d=await r.json()}catch{}
 if(!r.ok){let e=new Error(d.message||'通信エラー');e.status=r.status;throw e}return d;
}
const protectedEl=(el)=><Protected>{el}</Protected>;
function Protected({children}){return sessionStorage.getItem('login')==='1'?children:<Navigate to="/login" replace/>}
function Layout({children}){const n=useNavigate();async function out(){try{await api('/logout',{method:'POST'})}catch{}sessionStorage.removeItem('login');n('/login')}return <><header><Link to="/top" className="brand">社員管理システム</Link><nav><Link to="/top">トップ</Link><Link to="/employees">社員一覧</Link><Link to="/employees/new">社員登録</Link><button onClick={out}>ログアウト</button></nav></header><main>{children}</main></>}
function Login(){const[id,setId]=useState(''),[pw,setPw]=useState(''),[err,setErr]=useState('');const n=useNavigate();async function sub(e){e.preventDefault();try{let d=await api('/login',{method:'POST',body:JSON.stringify({login_id:id,password:pw})});if(!d.success)return setErr(d.message);sessionStorage.setItem('login','1');n('/top')}catch(e){setErr(e.message)}}return <div className="login"><form className="card loginCard" onSubmit={sub}><span className="eyebrow">EMPLOYEE MANAGEMENT</span><h1>社員管理システム</h1><p>管理者ログイン</p>{err&&<div className="error">{err}</div>}<label>ログインID<input value={id} onChange={e=>setId(e.target.value)}/></label><label>パスワード<input type="password" value={pw} onChange={e=>setPw(e.target.value)}/></label><button className="primary">ログイン</button><small>テスト: admin / admin123</small></form></div>}
function Top(){return <Layout><Title en="DASHBOARD" title="トップページ" text="社員情報の管理を行います。"/><div className="grid"><Link className="menu" to="/employees"><b>01</b><h2>社員一覧</h2><p>社員情報の確認・編集・削除</p></Link><Link className="menu" to="/employees/new"><b>02</b><h2>社員登録</h2><p>新しい社員情報を登録</p></Link></div></Layout>}
function Title({en,title,text,action}){return <div className="title"><div><span className="eyebrow">{en}</span><h1>{title}</h1>{text&&<p>{text}</p>}</div>{action}</div>}
function Employees(){const[es,setEs]=useState([]),[err,setErr]=useState('');const n=useNavigate();async function load(){try{setEs(await api('/employees'))}catch(e){if(e.status===401){sessionStorage.removeItem('login');n('/login')}else setErr(e.message)}}useEffect(()=>{load()},[]);async function del(id){if(!confirm('この社員を削除しますか？'))return;try{await api('/employees/'+id,{method:'DELETE'});load()}catch(e){setErr(e.message)}}return <Layout><Title en="EMPLOYEES" title="社員一覧" text="登録されている社員を確認できます。" action={<Link className="primary button" to="/employees/new">＋ 社員登録</Link>}/>{err&&<div className="error">{err}</div>}<div className="card tableWrap"><table><thead><tr><th>ID</th><th>氏名</th><th>部署</th><th>役職</th><th>メール</th><th>操作</th></tr></thead><tbody>{es.map(e=><tr key={e.employee_id}><td>{e.employee_id}</td><td><strong>{e.name}</strong></td><td>{e.department}</td><td>{e.position||'-'}</td><td>{e.email}</td><td><Link className="blue" to={'/employees/'+e.employee_id}>詳細</Link> <button className="red" onClick={()=>del(e.employee_id)}>削除</button></td></tr>)}</tbody></table></div></Layout>}
function Detail(){const{id}=useParams(),[e,setE]=useState(null),[err,setErr]=useState('');useEffect(()=>{api('/employees/'+id).then(setE).catch(x=>setErr(x.message))},[id]);return <Layout><Title en="DETAIL" title="社員詳細"/>{err&&<div className="error">{err}</div>}{e&&<div className="card detail">{[['社員ID',e.employee_id],['氏名',e.name],['部署',e.department],['役職',e.position||'-'],['メールアドレス',e.email]].map(x=><div className="row" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}<div className="actions"><Link className="secondary button" to="/employees">一覧へ戻る</Link><Link className="primary button" to={'/employees/'+id+'/edit'}>編集する</Link></div></div>}</Layout>}
function Form({edit=false}){const{id}=useParams(),n=useNavigate();const[f,setF]=useState({name:'',department:'',position:'',email:''}),[err,setErr]=useState('');useEffect(()=>{if(edit)api('/employees/'+id).then(e=>setF({name:e.name,department:e.department,position:e.position||'',email:e.email})).catch(e=>setErr(e.message))},[edit,id]);function c(k,v){setF({...f,[k]:v})}async function sub(ev){ev.preventDefault();try{await api(edit?'/employees/'+id:'/employees',{method:edit?'PUT':'POST',body:JSON.stringify(f)});n(edit?'/employees/'+id:'/employees')}catch(e){setErr(e.message)}}return <Layout><Title en={edit?'EDIT':'REGISTER'} title={edit?'社員編集':'社員登録'}/><form className="card form" onSubmit={sub}>{err&&<div className="error">{err}</div>}<label>氏名 *<input required value={f.name} onChange={e=>c('name',e.target.value)}/></label><label>部署 *<select required value={f.department} onChange={e=>c('department',e.target.value)}><option value="">選択</option><option>営業部</option><option>開発部</option><option>総務部</option></select></label><label>役職<input value={f.position} onChange={e=>c('position',e.target.value)}/></label><label>メールアドレス *<input required type="email" value={f.email} onChange={e=>c('email',e.target.value)}/></label><div className="actions"><button type="button" className="secondary" onClick={()=>n(edit?'/employees/'+id:'/top')}>キャンセル</button><button className="primary">{edit?'更新する':'登録する'}</button></div></form></Layout>}
function App(){return <Routes><Route path="/" element={<Navigate to="/login"/>}/><Route path="/login" element={<Login/>}/><Route path="/top" element={protectedEl(<Top/>)}/><Route path="/employees" element={protectedEl(<Employees/>)}/><Route path="/employees/new" element={protectedEl(<Form/>)}/><Route path="/employees/:id" element={protectedEl(<Detail/>)}/><Route path="/employees/:id/edit" element={protectedEl(<Form edit/>)}/><Route path="*" element={<Navigate to="/login"/>}/></Routes>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
